//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarAccessControl.Application.Common.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CarAccessControl.Application.Common.Localization.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera ID.
        /// </summary>
        internal static string Property_CameraId {
            get {
                return ResourceManager.GetString("Property_CameraId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame Interval.
        /// </summary>
        internal static string Property_FrameInterval {
            get {
                return ResourceManager.GetString("Property_FrameInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gate Name.
        /// </summary>
        internal static string Property_GateName {
            get {
                return ResourceManager.GetString("Property_GateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        internal static string Property_Ip {
            get {
                return ResourceManager.GetString("Property_Ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Status.
        /// </summary>
        internal static string Property_IsActive {
            get {
                return ResourceManager.GetString("Property_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Property_Location {
            get {
                return ResourceManager.GetString("Property_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner ID.
        /// </summary>
        internal static string Property_OwnerId {
            get {
                return ResourceManager.GetString("Property_OwnerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Plate.
        /// </summary>
        internal static string Property_PlateNumber {
            get {
                return ResourceManager.GetString("Property_PlateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTSP/Stream URL.
        /// </summary>
        internal static string Property_Url {
            get {
                return ResourceManager.GetString("Property_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Name.
        /// </summary>
        internal static string Property_VehicleName {
            get {
                return ResourceManager.GetString("Property_VehicleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to “{PropertyName}” must be exactly {MaxLength} characters..
        /// </summary>
        internal static string Validation_ExactLength {
            get {
                return ResourceManager.GetString("Validation_ExactLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to “{PropertyName}” must be greater than {ComparisonValue}..
        /// </summary>
        internal static string Validation_GreaterThan {
            get {
                return ResourceManager.GetString("Validation_GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid IP address format..
        /// </summary>
        internal static string Validation_IpInvalid {
            get {
                return ResourceManager.GetString("Validation_IpInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to “{PropertyName}” must be between {MinLength} and {MaxLength} characters..
        /// </summary>
        internal static string Validation_Length {
            get {
                return ResourceManager.GetString("Validation_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to “{PropertyName}” must not exceed {MaxLength} characters..
        /// </summary>
        internal static string Validation_MaxLength {
            get {
                return ResourceManager.GetString("Validation_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to “{PropertyName}” must contain only numbers..
        /// </summary>
        internal static string Validation_Numeric {
            get {
                return ResourceManager.GetString("Validation_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid license plate format..
        /// </summary>
        internal static string Validation_PlateInvalid {
            get {
                return ResourceManager.GetString("Validation_PlateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to “{PropertyName}” is required..
        /// </summary>
        internal static string Validation_Required {
            get {
                return ResourceManager.GetString("Validation_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL format..
        /// </summary>
        internal static string Validation_UrlInvalid {
            get {
                return ResourceManager.GetString("Validation_UrlInvalid", resourceCulture);
            }
        }
    }
}
